### ISSUE TITLE
add node shebang

### ISSUE THREAD

**Issue by ssube** [ssube/rollup-template#9]
A proper shebang would allow the index script to be executed directly, rather than through `CMD ["node", "/app/index.js"]`. However, the shebang needs to be compatible with both node and mocha/chrome, since the same output is used everywhere. This is close:

```
#!/bin/sh
':' //; exec "$(command -v node)" "$0" "$@
```

from https://unix.stackexchange.com/questions/65235/universal-node-js-shebang/65295#65295, but still results in a syntax error during `make test`:

```
/home/ssube/code/ssube/rollup-template//node_modules/.bin/nyc --reporter=lcov --reporter=text-summary --reporter=html --report-dir="/home/ssube/code/ssube/n
oicejs//out/coverage" --exclude-after-remap /home/ssube/code/ssube/rollup-template//node_modules/.bin/mocha --check-leaks --colors --sort --ui bdd /home/ssu
be/code/ssube/rollup-template//out/test.js                                                                                             
/home/ssube/code/ssube/rollup-template/out/test.js:2                                                              
#!/bin/sh                                                                                         
^                                                                                             

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Module.replacementCompile (/home/ssube/code/ssube/rollup-template/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.<anonymous> (/home/ssube/code/ssube/rollup-template/node_modules/append-transform/index.js:62:4)
```

**Comment by ssube** [comment]
The `build-bundle` target now adds a shebang to index: `sed -i '1s;^;#! /usr/bin/env node\n\n;' $(TARGET_PATH)/index.js`
